version: '3'
services:
  db:
    image: postgres
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
  app:
    build: .
    command: puma
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    depends_on:
      - db
  node:
    image: 'node:9.11'
    volumes:
      - './:/app'
    working_dir: /app
